if [ -f ~/.bashrc ];
then
    source ~/.bashrc
fi
##
# Your previous /Users/sergio/.bash_profile file was backed up as /Users/sergio/.bash_profile.macports-saved_2010-08-09_at_04:05:37
##

# MacPorts Installer addition on 2010-08-09_at_04:05:37: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.


##
# Your previous /Users/sergio/.bash_profile file was backed up as /Users/sergio/.bash_profile.macports-saved_2010-08-16_at_04:34:12
##

# MacPorts Installer addition on 2010-08-16_at_04:34:12: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.


# Setting PATH for Python 2.7
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/2.7/bin:${PATH}"
export PATH
