# Symlink to this file from ~/.bashrc

. ~/bin/dotfiles/bash/env
. ~/bin/dotfiles/bash/config
. ~/bin/dotfiles/bash/aliases

# Bashmarks: http://www.huyng.com/bashmarks-directory-bookmarks-for-the-shell/
. ~/.local/bin/bashmarks.sh