# This following line is needed for remote git commands do not remove.
export PATH=${PATH}:/usr/local/git/bin:/usr/local/libexec/git-core

# Maven HOME and PATH
export M2_HOME=/usr/local/apache-maven-2.2.1
M2=/bin
echo Cargado: .bashrc

# history settings
export HISTCONTROL=erasedups
export HISTSIZE=1000
shopt -s histappend

# VI mode for command line editing
#set -o vi

# Do not overwrite files when redirecting output
set -o noclobber

# save and restore working dir
alias sd="pwd > ~/.sd"
alias ds="cd `cat ~/.sd`" 
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'

#export EDITOR="mate -w"
export EDITOR=vim

export PATH=/usr/local/git/bin:$PATH
export PATH=$PATH:/opt/local/bin
export PATH=$PATH:~/bin
export PATH=$PATH:/usr/local/mysql/bin
export MANPATH=/usr/local/git/man:$MANPATH
export MANPATH=/usr/local/mysql/man:$MANPATH
export MANPATH=$MANPATH:/opt/local/man
export PYTHONPATH="$HOME/lib/python"
export PYTHONSTARTUP="$HOME/.pythonrc.py"
PS1="\n[\W]$ "

# La siguiente línea es necesitada por Limp (Vim Lisp)
export LIMPRUNTIME=/usr/local/limp-0.3.3

export PYTHONDOCS=/Users/sergio/Documents/Reference/Python-Docs-2.5

# ver man pages de ls para la expliación de LSCOLORS
export LSCOLORS=gxfxcxdxbxegedabagacad

alias ls="ls -GF"
alias lss="ls -GathorF"

. cdargs-bash.sh
alias cd..='cd ..'
# Bind tab to autocomplete instead of listing
bind '"\t":menu-complete'

# Encoding para hg y svn
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

 #Derby Home
export DERBY_HOME=/usr/share/derby

export M2_HOME=/usr/local/apache-maven-2.2.1
M2=/bin
PATH=/opt/local/bin:/opt/local/sbin::/usr/local/git/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin:/opt/local/bin:/usr/local/git/bin:/opt/local/bin:/Users/sergio/bin:/usr/local/mysql/bin:$DERBY_HOME/bin:$PATH

##
# Your previous /Users/sergio/.bash_profile file was backed up as /Users/sergio/.bash_profile.macports-saved_2009-11-02_at_02:22:10
##

# MacPorts Installer addition on 2009-11-02_at_02:22:10: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.


# Java 
export JAVA_HOME=$(/usr/libexec/java_home)

alias tree2="tree -L 2"
alias tree3="tree -L 3"

# comandos personales de mercurial
alias hgst='hg status $(hg root) -n'

# Scala
export PATH=$PATH:/usr/local/scala/bin
echo Cargado: .bash_profile
